# Generated by Django 5.2.13 on 2026-04-20 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportUploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_file', models.FileField(upload_to='imports/uploads/%Y/%m/%d/')),
                ('source_hash', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PREVIEWED', 'Previewed'), ('EXECUTED', 'Executed'), ('EXPIRED', 'Expired')], default='UPLOADED', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('selected_sheets', models.JSONField(blank=True, default=list)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('executed_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_upload_sessions', to='data_imports.importjob')),
                ('preview_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preview_upload_sessions', to='data_imports.importjob')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
