# Generated by Django 5.2.13 on 2026-04-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_imports', '0002_importuploadsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('CANCELLED', 'Cancelled'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='importsheetresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('CANCELLED', 'Cancelled'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
