# Generated by Django 6.0.4 on 2026-04-10 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelWorkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deshabitada', models.CharField(blank=True, max_length=30)),
                ('cercada', models.CharField(blank=True, max_length=30)),
                ('sucia', models.CharField(blank=True, max_length=30)),
                ('casas', models.CharField(blank=True, max_length=80)),
                ('otra_construccion', models.CharField(blank=True, max_length=120)),
                ('cumplen', models.CharField(blank=True, max_length=30)),
                ('cortafuego', models.CharField(blank=True, max_length=30)),
                ('limpieza', models.CharField(blank=True, max_length=30)),
                ('foco_incendio', models.CharField(blank=True, choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], max_length=10)),
                ('atributo_kpi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('kpi', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('ATENCION', 'Atención'), ('PELIGRO', 'Peligro')], max_length=20)),
                ('estado_actual', models.CharField(blank=True, max_length=120)),
                ('rol_sii', models.CharField(blank=True, max_length=80)),
                ('certificado_obras', models.CharField(blank=True, max_length=30)),
                ('permiso_dom', models.CharField(blank=True, max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parcela', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_status', to='parcels.parcel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
