# Generated by Django 6.0.4 on 2026-04-10 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('ADMINISTRATIVA', 'Administrativa'), ('COBRANZA', 'Cobranza'), ('OPERATIVA', 'Operativa'), ('ALERTA', 'Alerta')], default='ADMINISTRATIVA', max_length=20)),
                ('texto', models.TextField()),
                ('fecha_evento', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='parcels.parcel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('usuario_registra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_evento', '-created_at'],
            },
        ),
    ]
