# Generated by Django 5.2.13 on 2026-04-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_actor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='actor_type',
            field=models.CharField(choices=[('GERENTE_GENERAL', 'Gerente general'), ('JEFE_OBRAS_COMUNIDAD', 'Jefe direccion de obras y comunidad'), ('JEFE_SEGURIDAD_OPERACIONAL', 'Jefe seguridad y operacional'), ('CENTRAL_MONITOREO', 'Operador central de monitoreo'), ('PORTAL_ACCESO', 'Portal de acceso'), ('OPERADOR_DRONE', 'Operador drone'), ('CONSULTA_EJECUTIVA', 'Consulta ejecutiva'), ('ADMIN_SISTEMA', 'Administrador de sistema')], default='CONSULTA_EJECUTIVA', max_length=40),
        ),
    ]
