# Generated by Django 6.0.4 on 2026-04-10 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombres', models.CharField(blank=True, max_length=120)),
                ('apellidos', models.CharField(blank=True, max_length=120)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('rut', models.CharField(blank=True, max_length=20)),
                ('rut_dv', models.CharField(blank=True, max_length=2)),
                ('rut_normalizado', models.CharField(blank=True, db_index=True, max_length=12)),
                ('telefono_principal', models.CharField(blank=True, max_length=30)),
                ('telefono_secundario', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion_contacto', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='ParcelResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tipo_residencia', models.CharField(choices=[('RESIDENTE', 'Residente'), ('CUIDADOR', 'Cuidador'), ('FAMILIAR', 'Familiar'), ('OTRO', 'Otro')], default='RESIDENTE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='parcels.parcel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_residencies', to='people.person')),
            ],
            options={
                'ordering': ['-is_active', 'persona__nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='ParcelOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('PRINCIPAL', 'Propietario principal'), ('COPROPIETARIO', 'Copropietario')], default='COPROPIETARIO', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='parcels.parcel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_ownerships', to='people.person')),
            ],
            options={
                'ordering': ['-tipo', 'persona__nombre_completo'],
            },
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('rut_normalizado__gt', ''), ('is_deleted', False)), fields=('rut_normalizado',), name='uniq_person_rut_normalizado_alive'),
        ),
        migrations.AddConstraint(
            model_name='parcelresident',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('parcela', 'persona', 'tipo_residencia'), name='uniq_active_resident_per_role'),
        ),
        migrations.AddConstraint(
            model_name='parcelownership',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'PRINCIPAL'), ('is_active', True), ('is_deleted', False)), fields=('parcela',), name='uniq_active_primary_owner_per_parcel'),
        ),
        migrations.AddConstraint(
            model_name='parcelownership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('parcela', 'persona', 'tipo'), name='uniq_active_owner_role_per_parcel_person'),
        ),
    ]
