# Generated by Django 6.0.4 on 2026-04-13 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_role', models.CharField(blank=True, max_length=20)),
                ('user_actor_type', models.CharField(blank=True, max_length=40)),
                ('action', models.CharField(choices=[('LIST', 'Listado'), ('RETRIEVE', 'Detalle'), ('CREATE', 'Creacion'), ('UPDATE', 'Actualizacion'), ('DELETE', 'Eliminacion'), ('CUSTOM', 'Accion custom')], db_index=True, max_length=20)),
                ('request_method', models.CharField(db_index=True, max_length=10)),
                ('request_path', models.CharField(db_index=True, max_length=255)),
                ('resource', models.CharField(blank=True, db_index=True, max_length=120)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status_code', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_success', models.BooleanField(db_index=True, default=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('response_summary', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='audits_audi_created_72c106_idx'), models.Index(fields=['action', 'request_method'], name='audits_audi_action_35ce69_idx'), models.Index(fields=['resource', 'object_id'], name='audits_audi_resourc_c15f42_idx'), models.Index(fields=['user', 'created_at'], name='audits_audi_user_id_764d75_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('LOGIN', 'Inicio de sesion'), ('LOGOUT', 'Cierre de sesion'), ('REFRESH', 'Refresh token'), ('PASSWORD_CHANGE', 'Cambio de contrasena')], db_index=True, max_length=30)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('auth_identifier', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='audits_user_created_1037bc_idx'), models.Index(fields=['action', 'success'], name='audits_user_action_095e0a_idx'), models.Index(fields=['user', 'created_at'], name='audits_user_user_id_34bcd0_idx')],
            },
        ),
    ]
