# Generated by Django 5.2.13 on 2026-04-13 14:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('parcels', '0002_alter_parcel_codigo_parcela_key_and_more'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('movement_type', models.CharField(choices=[('INCOME', 'Ingreso'), ('EXPENSE', 'Egreso')], db_index=True, default='INCOME', max_length=20)),
                ('category', models.CharField(choices=[('PAYMENT_GC', 'Pago gasto común'), ('PAYMENT_SERVICE', 'Pago servicio/AYS'), ('PAYMENT_AGREEMENT', 'Pago convenio'), ('PAYMENT_FINE', 'Pago multa'), ('OTHER_INCOME', 'Otro ingreso'), ('OPERATIONAL_EXPENSE', 'Egreso operacional'), ('MAINTENANCE_EXPENSE', 'Egreso mantención'), ('SECURITY_EXPENSE', 'Egreso seguridad'), ('OTHER_EXPENSE', 'Otro egreso')], db_index=True, default='OTHER_INCOME', max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('TRANSFER', 'Transferencia'), ('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('ONLINE', 'Pago online'), ('OTHER', 'Otro')], default='TRANSFER', max_length=20)),
                ('is_confirmed', models.BooleanField(db_index=True, default=True)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('source_label', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parcela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_movements', to='parcels.parcel')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_movements', to='people.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
    ]
