# Generated by Django 6.0.4 on 2026-04-10 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('codigo_parcela', models.CharField(max_length=20, unique=True)),
                ('codigo_parcela_key', models.CharField(db_index=True, max_length=20, unique=True)),
                ('letra_lote', models.CharField(db_index=True, max_length=3)),
                ('numero_lote', models.PositiveIntegerField(db_index=True)),
                ('sufijo_lote', models.CharField(blank=True, default='', max_length=2)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('SUSPENDIDA', 'Suspendida')], db_index=True, default='ACTIVA', max_length=20)),
                ('referencia_direccion', models.CharField(blank=True, max_length=255)),
                ('observaciones_generales', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['letra_lote', 'numero_lote', 'sufijo_lote'],
            },
        ),
    ]
