# Generated by Django 6.0.4 on 2026-04-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='codigo_parcela_key',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='letra_lote',
            field=models.CharField(blank=True, db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='numero_lote',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
