# Generated by Django 6.0.4 on 2026-04-10 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ppu', models.CharField(max_length=20)),
                ('ppu_normalizado', models.CharField(db_index=True, max_length=20)),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('tipo', models.CharField(blank=True, max_length=80)),
                ('color', models.CharField(blank=True, max_length=80)),
                ('codigo_acceso', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='parcels.parcel')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='people.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ppu_normalizado'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('parcela', 'ppu_normalizado'), name='uniq_vehicle_parcel_ppu_alive')],
            },
        ),
    ]
